
function YourWorkouts() {
  return (
    <>
        <h1>Your Workouts</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt lorem quis sem accumsan feugiat. Sed tempor, arcu ut euismod finibus, sapien tellus vulputate libero, a lobortis urna justo vitae elit. Duis non nunc erat. Integer suscipit, erat sit amet gravida commodo, augue ex fringilla eros, sed facilisis ipsum nibh id mauris. Fusce erat tellus, ultricies quis lectus in, efficitur finibus tortor. Duis at erat tempus ex euismod lobortis sit amet a augue. Mauris vel risus magna.

Duis erat ante, semper eget turpis et, consequat fermentum lorem. Morbi convallis tristique nulla, ut volutpat felis congue eleifend. Phasellus turpis massa, luctus ac leo in, consectetur dignissim velit. Aenean bibendum sed quam sed euismod. Ut mattis erat vel nibh interdum, sit amet luctus mi pretium. Vivamus lectus lorem, semper eget placerat a, ultrices sit amet mi. In fringilla nibh ut sodales malesuada. Ut ac sapien a mauris sodales suscipit. Praesent ultricies laoreet vehicula. Pellentesque vel lacinia nisl. Suspendisse aliquam dictum elit, sed varius ante dapibus in. Sed faucibus sagittis porta. Nulla blandit leo quis dui rhoncus, vel ullamcorper massa porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus in iaculis lacus, vel suscipit enim. Fusce ac nulla pretium, commodo orci nec, sollicitudin sapien.

In ipsum tortor, scelerisque a erat at, luctus molestie arcu. Phasellus non metus risus. Donec feugiat in quam a bibendum. Etiam convallis porttitor purus, aliquet euismod elit ultrices nec. Aliquam blandit pellentesque ipsum ac fermentum. Morbi pharetra egestas dolor nec euismod. Quisque mi nisl, fringilla eget maximus eu, tempor in leo. Donec ornare ultrices tortor sed semper. In tortor est, ultrices ut turpis eget, imperdiet dignissim velit. Duis mattis bibendum ex id consectetur. Donec vel placerat nunc. Phasellus dictum hendrerit laoreet. Sed quis efficitur arcu. Praesent sed eros lorem. Sed fringilla ipsum sit amet ipsum placerat bibendum ac in metus.

Maecenas bibendum laoreet varius. Vestibulum ut diam vitae ante consequat malesuada. Quisque dolor urna, condimentum ut malesuada et, condimentum quis dui. Nam tincidunt magna sem, ac tincidunt neque molestie sed. Donec ante magna, egestas at magna at, varius vulputate elit. Integer feugiat vitae est id faucibus. Curabitur cursus sed risus id sodales. Fusce sed quam quam. Etiam eget felis malesuada, interdum orci at, laoreet quam. Ut scelerisque sodales odio, ac lacinia velit. Ut rutrum ullamcorper blandit. Sed interdum magna et egestas tristique.

Nulla eu sodales justo, vel ultrices tellus. Morbi eget urna in diam gravida posuere ac in augue. Quisque dictum nulla sit amet gravida ultricies. Maecenas aliquam diam id arcu auctor, id viverra erat convallis. Aenean sed urna orci. Aliquam semper ultrices purus, nec tristique arcu laoreet eu. Nunc sed nibh vel lectus vestibulum pellentesque at sit amet ex. Nullam venenatis ipsum massa, non pretium massa imperdiet nec. Aliquam massa ipsum, lobortis ut malesuada sit amet, tempor id risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed commodo ac magna non vestibulum. Pellentesque in ullamcorper nunc. Sed hendrerit, ligula non cursus molestie, nisi purus cursus sapien, sed sollicitudin lectus dui non ante. Suspendisse at iaculis diam, eu porttitor ante. Nunc nec finibus nibh.

Sed vestibulum lobortis sollicitudin. Quisque arcu massa, consequat eget fermentum rutrum, vulputate eget nulla. Aliquam erat volutpat. Ut facilisis, magna eu consectetur egestas, nisi lacus vulputate arcu, in efficitur nibh nulla vel dui. Donec et ante ut ligula ornare convallis. Pellentesque nibh nunc, fermentum et lacus semper, faucibus convallis velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris massa magna, malesuada a rhoncus vel, ultricies ut augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vitae lectus pulvinar tellus vulputate viverra a et leo. Curabitur vehicula euismod accumsan. Aliquam facilisis erat nec mattis ultrices. Fusce consequat libero nisi, ut tincidunt eros maximus commodo. Morbi condimentum elit eget varius ullamcorper. Integer elementum rutrum magna sit amet iaculis.

Aliquam erat volutpat. Nam ut felis a dui faucibus malesuada. Cras in scelerisque nulla. Sed consectetur ligula eget dolor dignissim mollis. Nulla sodales porta magna at suscipit. Proin auctor condimentum purus, sit amet viverra lorem ullamcorper sit amet. Duis ullamcorper eget felis nec hendrerit. Donec est ipsum, consectetur a tempus quis, sodales non diam.

Integer in dui id sapien pellentesque dictum. Sed sit amet felis mauris. Vestibulum metus justo, elementum non semper nec, sagittis a massa. Ut convallis consequat condimentum. Vivamus nec dui at dui suscipit elementum. Maecenas eleifend nisi non nisi bibendum sagittis. Fusce gravida hendrerit ipsum quis finibus. Mauris turpis nulla, feugiat et viverra sed, commodo eu ex. Donec iaculis dui diam, quis rhoncus metus vulputate a. Nullam dapibus ultricies erat at semper. Integer ut ultricies purus.

Nunc massa est, efficitur vel est et, semper scelerisque sem. Phasellus vel molestie mauris, nec malesuada neque. Maecenas suscipit in velit sit amet vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla blandit mi eget mauris porta suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut est quam, egestas nec augue ut, tincidunt vehicula metus. Fusce egestas massa mauris, vitae fermentum quam efficitur et. Mauris condimentum lacinia arcu, elementum luctus sapien pretium non. Cras posuere eu urna in elementum. Mauris non leo orci. Pellentesque ullamcorper nulla at eros blandit elementum.

Nullam nec dui efficitur, condimentum mi eget, pulvinar augue. Fusce justo dolor, aliquam ac suscipit non, pulvinar sit amet elit. Pellentesque vel pretium leo. Vestibulum viverra cursus purus vitae vulputate. Integer erat nisi, sodales vel diam convallis, iaculis imperdiet sapien. Quisque tincidunt libero risus, vel tincidunt quam finibus at. Donec pulvinar nibh in massa vehicula, sit amet porttitor erat auctor. Proin faucibus lacinia purus et ultricies. Proin et porta felis, in convallis lacus. Fusce sit amet viverra ipsum, ut efficitur est. Pellentesque elit diam, commodo non sagittis in, ultricies id magna. Quisque a sollicitudin tortor. Cras dictum tristique nulla non rhoncus. Donec bibendum tristique leo, sed scelerisque sem pellentesque id. Aliquam erat volutpat. Aenean pharetra, neque in cursus scelerisque, purus sapien dignissim dolor, auctor posuere lacus mauris id orci</p>
    </>
  )
}

export default YourWorkouts